version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mypostgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0684
      - POSTGRES_DB=dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: dash_back
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # volumes 항목 제거: 이미지에 복사한 파일들이 유지됩니다.
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:0684@db:5432/dashboard

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mypgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pxj0684@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=0684
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: