FROM jenkins/jenkins:lts

USER root

# apt-get 업데이트 후, docker.io와 awscli 설치
RUN apt-get update && \
    apt-get install -y docker.io awscli && \
    apt-get clean

# 빌드 시 전달받은 DOCKER_GID 값을 사용하여 docker 그룹 생성
ARG DOCKER_GID=999
RUN groupadd -f -g ${DOCKER_GID} docker && \
    usermod -aG docker jenkins

USER jenkins
