# Dockerfile.jenkins-docker-aws

FROM jenkins/jenkins:lts

# Root 사용자로 전환하여 패키지 설치
USER root

# apt-get 업데이트 후, docker.io와 awscli 설치
RUN apt-get update && \
    apt-get install -y docker.io awscli && \
    apt-get clean

# Jenkins 사용자(일반적으로 "jenkins")를 docker 그룹에 추가하여 docker 명령 사용 권한 부여
RUN usermod -aG docker jenkins

# 필요한 경우 추가 패키지 설치 (예: git 등)

# 기본 명령어는 Jenkins 이미지에 이미 정의되어 있으므로 그대로 사용
USER jenkins
